### ISSUE TITLE
希望添加对 Android Studio 2021.1.1 支持

### ISSUE THREAD

**Issue by MarnoDev** [cr1992/FlutterAssetsGenerator#1]
Flutter 上用起来最舒服的图片资源插件了，希望可以更新一下

![image](https://user-images.githubusercontent.com/14787921/144535421-29731534-5bcd-4694-a585-1b6e8f5f00c5.png)

![image](https://user-images.githubusercontent.com/14787921/144535567-f7c073da-5643-4e5d-b7c6-4ce54ac1ea23.png)

**Comment by cr1992** [comment]
你这用的还是beta版，我看看能不能把untilVersion给去掉

**Comment by cr1992** [comment]
新版本提交上去了，应该可以了

**Comment by MarnoDev** [comment]
可以了，爆赞
