### ISSUE TITLE
problem with variable names

### ISSUE THREAD

**Issue by CuongNV12** [cr1992/FlutterAssetsGenerator#2]
I have assets file with "-" character in name, when its reference is created it shows error in variable name.
I'm fixing it by renaming the file "-" to "_", but I don't want to do that manually, what I want is the plugin to be able to automatically rename the reference file.
Can you add it?

![image](https://user-images.githubusercontent.com/53120409/165243872-1c805b60-d3e9-4f3c-87e2-e60d7d8707ed.png)

**Comment by cr1992** [comment]
supported
