### ISSUE TITLE
[Future]希望添加一个配置信息，确定pubspec.yaml以及项目位置

### ISSUE THREAD

**Issue by azhansy** [cr1992/FlutterAssetsGenerator#20]
- 根目录
  -- 所有项目依赖的core
  -- 相同项目下
     --- 司机端A项目
     --- 乘客端B项目
     --- xxx端C项目
  
能够配置 pubspec.yaml 以及对应的项目路径。

**Comment by cr1992** [comment]
不是很理解你的需求，目前会有什么问题不

**Comment by jhfkf** [comment]
他是想直接在资源前面加上packages名字  例如： packages/xxx/assets/images/xxx.png

**Comment by jhfkf** [comment]
就是 资源前面 加一个 固定前缀

**Comment by azhansy** [comment]
忽略～本意是支持多个项目，不是添加前缀。
