### ISSUE TITLE
Android Studio Chipmunk 2021.2.1 This Project is not a Flutter Project

### ISSUE THREAD

**Issue by ChivialK** [cr1992/FlutterAssetsGenerator#3]
<img width="728" alt="截圖 2022-06-07 下午2 00 43拷貝" src="https://user-images.githubusercontent.com/8535276/172310565-c6319d02-8b08-433c-a01f-75d737707cea.png">

<img width="369" alt="截圖 2022-06-07 下午2 20 37" src="https://user-images.githubusercontent.com/8535276/172309933-abc48b5e-4e10-4e50-8d67-cf0712095225.png">

Any idea how to fix this?
My project folder was created by using the command line
`flutter create .`

**Comment by cr1992** [comment]
fixed , try again.
