### ISSUE TITLE
pubspec.yaml中没写的目录下的文件可以不生成么

### ISSUE THREAD

**Issue by endison1986** [cr1992/FlutterAssetsGenerator#4]
pubspec.yaml中没写的目录下的文件可以不生成么，只先了一个目录，比如assets/images，但把assets/和assets/fonts下的文件全部都生成了

**Comment by Dean-Spotec** [comment]
确实有这个需求，无用的font文件和lottie文件也被引入了

**Comment by cr1992** [comment]
> 确实有这个需求，无用的font文件和lottie文件也被引入了

生成的path为啥用不上呢？不想和图片资源弄混是吗？

**Comment by Dean-Spotec** [comment]
lottie文件主要是名字可能冲突，这个好解决。但是font就比较烦，比如会生成这样的路径
<img width="740" alt="image" src="https://user-images.githubusercontent.com/75231684/204190498-88d7d8b8-7d26-4c53-8ff1-d4436c8571ea.png">
首先首字母大写无法通过项目中配置的linter，其次实际使用时直接指定fontFamily字符串即可
```
TextStyle(fontFamily: 'RubikMedium')
```

**Comment by cr1992** [comment]
添加目录过滤配置，over，更新一下版本就好
